name: http1
version: 0.1.0.0
github: "githubuser/http1"
license: BSD3
author: "Andrii Maliuta"
maintainer: "quadr988@gmail.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/http1#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  http1-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - http1

tests:
  http1-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - http1
